// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.13.0
// source: movie/controller/rpc/pb/movie.proto

package pb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type MovieSearchSpec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Keyword string `protobuf:"bytes,1,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Page    int64  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *MovieSearchSpec) Reset() {
	*x = MovieSearchSpec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_controller_grpc_pb_movie_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieSearchSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieSearchSpec) ProtoMessage() {}

func (x *MovieSearchSpec) ProtoReflect() protoreflect.Message {
	mi := &file_movie_controller_grpc_pb_movie_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieSearchSpec.ProtoReflect.Descriptor instead.
func (*MovieSearchSpec) Descriptor() ([]byte, []int) {
	return file_movie_controller_grpc_pb_movie_proto_rawDescGZIP(), []int{0}
}

func (x *MovieSearchSpec) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *MovieSearchSpec) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type MovieSearchResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Search       []*MovieDisplay `protobuf:"bytes,1,rep,name=Search,proto3" json:"Search,omitempty"`
	TotalResults int64           `protobuf:"varint,2,opt,name=TotalResults,proto3" json:"TotalResults,omitempty"`
	Response     bool            `protobuf:"varint,3,opt,name=Response,proto3" json:"Response,omitempty"`
}

func (x *MovieSearchResponse) Reset() {
	*x = MovieSearchResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_controller_grpc_pb_movie_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieSearchResponse) ProtoMessage() {}

func (x *MovieSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_movie_controller_grpc_pb_movie_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieSearchResponse.ProtoReflect.Descriptor instead.
func (*MovieSearchResponse) Descriptor() ([]byte, []int) {
	return file_movie_controller_grpc_pb_movie_proto_rawDescGZIP(), []int{1}
}

func (x *MovieSearchResponse) GetSearch() []*MovieDisplay {
	if x != nil {
		return x.Search
	}
	return nil
}

func (x *MovieSearchResponse) GetTotalResults() int64 {
	if x != nil {
		return x.TotalResults
	}
	return 0
}

func (x *MovieSearchResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

type MovieDisplay struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Title  string `protobuf:"bytes,1,opt,name=Title,proto3" json:"Title,omitempty"`
	Year   string `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	ImdbID string `protobuf:"bytes,3,opt,name=ImdbID,proto3" json:"ImdbID,omitempty"`
	Type   string `protobuf:"bytes,4,opt,name=Type,proto3" json:"Type,omitempty"`
	Poster string `protobuf:"bytes,5,opt,name=Poster,proto3" json:"Poster,omitempty"`
}

func (x *MovieDisplay) Reset() {
	*x = MovieDisplay{}
	if protoimpl.UnsafeEnabled {
		mi := &file_movie_controller_grpc_pb_movie_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MovieDisplay) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MovieDisplay) ProtoMessage() {}

func (x *MovieDisplay) ProtoReflect() protoreflect.Message {
	mi := &file_movie_controller_grpc_pb_movie_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MovieDisplay.ProtoReflect.Descriptor instead.
func (*MovieDisplay) Descriptor() ([]byte, []int) {
	return file_movie_controller_grpc_pb_movie_proto_rawDescGZIP(), []int{2}
}

func (x *MovieDisplay) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *MovieDisplay) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *MovieDisplay) GetImdbID() string {
	if x != nil {
		return x.ImdbID
	}
	return ""
}

func (x *MovieDisplay) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MovieDisplay) GetPoster() string {
	if x != nil {
		return x.Poster
	}
	return ""
}

var File_movie_controller_grpc_pb_movie_proto protoreflect.FileDescriptor

var file_movie_controller_grpc_pb_movie_proto_rawDesc = []byte{
	0x0a, 0x24, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x2f, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3f, 0x0a, 0x0f, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x70, 0x65, 0x63, 0x12, 0x18, 0x0a,
	0x07, 0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x7f, 0x0a, 0x13, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x28, 0x0a, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x10, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x69, 0x73,
	0x70, 0x6c, 0x61, 0x79, 0x52, 0x06, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x12, 0x22, 0x0a, 0x0c,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x73,
	0x12, 0x1a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x7c, 0x0a, 0x0c,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x69, 0x73, 0x70, 0x6c, 0x61, 0x79, 0x12, 0x14, 0x0a, 0x05,
	0x54, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x59, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x59, 0x65, 0x61, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x49, 0x6d, 0x64, 0x62, 0x49, 0x44,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x49, 0x6d, 0x64, 0x62, 0x49, 0x44, 0x12, 0x12,
	0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x32, 0x4d, 0x0a, 0x0c, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3d, 0x0a, 0x0b, 0x53, 0x65,
	0x61, 0x72, 0x63, 0x68, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12, 0x13, 0x2e, 0x70, 0x62, 0x2e, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x53, 0x70, 0x65, 0x63, 0x1a, 0x17,
	0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_movie_controller_grpc_pb_movie_proto_rawDescOnce sync.Once
	file_movie_controller_grpc_pb_movie_proto_rawDescData = file_movie_controller_grpc_pb_movie_proto_rawDesc
)

func file_movie_controller_grpc_pb_movie_proto_rawDescGZIP() []byte {
	file_movie_controller_grpc_pb_movie_proto_rawDescOnce.Do(func() {
		file_movie_controller_grpc_pb_movie_proto_rawDescData = protoimpl.X.CompressGZIP(file_movie_controller_grpc_pb_movie_proto_rawDescData)
	})
	return file_movie_controller_grpc_pb_movie_proto_rawDescData
}

var file_movie_controller_grpc_pb_movie_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_movie_controller_grpc_pb_movie_proto_goTypes = []interface{}{
	(*MovieSearchSpec)(nil),     // 0: pb.MovieSearchSpec
	(*MovieSearchResponse)(nil), // 1: pb.MovieSearchResponse
	(*MovieDisplay)(nil),        // 2: pb.MovieDisplay
}
var file_movie_controller_grpc_pb_movie_proto_depIdxs = []int32{
	2, // 0: pb.MovieSearchResponse.Search:type_name -> pb.MovieDisplay
	0, // 1: pb.MovieService.SearchMovie:input_type -> pb.MovieSearchSpec
	1, // 2: pb.MovieService.SearchMovie:output_type -> pb.MovieSearchResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_movie_controller_grpc_pb_movie_proto_init() }
func file_movie_controller_grpc_pb_movie_proto_init() {
	if File_movie_controller_grpc_pb_movie_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_movie_controller_grpc_pb_movie_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieSearchSpec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_controller_grpc_pb_movie_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieSearchResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_movie_controller_grpc_pb_movie_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MovieDisplay); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_movie_controller_grpc_pb_movie_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_movie_controller_grpc_pb_movie_proto_goTypes,
		DependencyIndexes: file_movie_controller_grpc_pb_movie_proto_depIdxs,
		MessageInfos:      file_movie_controller_grpc_pb_movie_proto_msgTypes,
	}.Build()
	File_movie_controller_grpc_pb_movie_proto = out.File
	file_movie_controller_grpc_pb_movie_proto_rawDesc = nil
	file_movie_controller_grpc_pb_movie_proto_goTypes = nil
	file_movie_controller_grpc_pb_movie_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MovieServiceClient is the client API for MovieService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MovieServiceClient interface {
	SearchMovie(ctx context.Context, in *MovieSearchSpec, opts ...grpc.CallOption) (*MovieSearchResponse, error)
}

type movieServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMovieServiceClient(cc grpc.ClientConnInterface) MovieServiceClient {
	return &movieServiceClient{cc}
}

func (c *movieServiceClient) SearchMovie(ctx context.Context, in *MovieSearchSpec, opts ...grpc.CallOption) (*MovieSearchResponse, error) {
	out := new(MovieSearchResponse)
	err := c.cc.Invoke(ctx, "/pb.MovieService/SearchMovie", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MovieServiceServer is the server API for MovieService service.
type MovieServiceServer interface {
	SearchMovie(context.Context, *MovieSearchSpec) (*MovieSearchResponse, error)
}

// UnimplementedMovieServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMovieServiceServer struct {
}

func (*UnimplementedMovieServiceServer) SearchMovie(context.Context, *MovieSearchSpec) (*MovieSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchMovie not implemented")
}

func RegisterMovieServiceServer(s *grpc.Server, srv MovieServiceServer) {
	s.RegisterService(&_MovieService_serviceDesc, srv)
}

func _MovieService_SearchMovie_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MovieSearchSpec)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MovieServiceServer).SearchMovie(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.MovieService/SearchMovie",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MovieServiceServer).SearchMovie(ctx, req.(*MovieSearchSpec))
	}
	return interceptor(ctx, in, info, handler)
}

var _MovieService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.MovieService",
	HandlerType: (*MovieServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchMovie",
			Handler:    _MovieService_SearchMovie_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "movie/controller/rpc/pb/movie.proto",
}
