version: "2.3"
services:
  dummy-postgres:
    image: postgres
    container_name: dummy-postgres
    volumes: 
      - ./:/sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=stkbit_app
      - POSTGRES_DB=stkbit
      - POSTGRES_PASSWORD=stkbit_app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U stkbit_app -D stkbit" ]
      interval: 10s
      timeout: 5s
      retries: 5
